env {
job.mode = "BATCH"
}
source {
Http {
url = "http://wso2server.huafeng.com:8280/huafon01/HttpService"
method = "post"
format = "json"
schema = {
fields = {
jlxwydl = "string"
calday = "bigint"
zxwl = "int"
xclydl = "string"
zxwl_210 = "string"
zfdl = "string"
pjglys = "string"
zxwl_200 = "string"
zhdl = "string"
alydl = "string"
}
}
json_field = {
jlxwydl = "$.data.result[*].fields.jlxwydl"
calday = "$.data.result[*].fields.calday"
zxwl = "$.data.result[*].fields.zxwl"
xclydl = "$.data.result[*].fields.xclydl"
zxwl_210 = "$.data.result[*].fields.zxwl_210"
zfdl = "$.data.result[*].fields.zfdl"
pjglys = "$.data.result[*].fields.pjglys"
zxwl_200 = "$.data.result[*].fields.zxwl_200"
zhdl = "$.data.result[*].fields.zhdl"
alydl = "$.data.result[*].fields.alydl"
}
keep_params_as_form = "true"
headers = {
content-type = "application/x-www-form-urlencoded"
token = "01FA871280D5DB91E0633801010AEF47"
}
params = {
actionmethod = "/FEISHU/DataExchange/Bitable/Query"
jsonstr = "{   'app_token': 'UeZFbNIfJarEjns1mQmcPipqnnb',   'configtablename': '配置表',   'datatablename': 'DQXTDL',   'searchField': {     'user_id_type': 'user_id',     'page_size': 5000,     'display_formula_ref': true   } }"
}
result_table_name = "华峰电气系统电量"
}
}
transform {
FieldMapper {
field_mapper = {
calday = "CALDAY"
zxwl_200 = "ZXWL_200"
zxwl_210 = "ZXWL_210"
zxwl = "ZXWL"
zhdl = "ZHDL"
pjglys = "PJGLYS"
alydl = "ALYDL"
xclydl = "XCLYDL"
jlxwydl = "JLXWYDL"
zfdl = "ZFDL"
}
source_table_name = "华峰电气系统电量"
result_table_name = "华峰电气系统电量_sink"
}
}
sink {
Doris {
source_table_name = "华峰电气系统电量_sink"
fenodes = "10.1.7.171:8030"
username = "root"
password = "doris@test123"
database = "ods"
table = "ODS_FS_DQXTDL_DF"
schema_save_mode = "CREATE_SCHEMA_WHEN_NOT_EXIST"
data_save_mode = "DROP_DATA"
save_mode_create_template = "CREATE TABLE IF NOT EXISTS `${database}`.`${table_name}` ( ${rowtype_fields} ) ENGINE=OLAP PROPERTIES ('replication_allocation'='tag.location.default:1');"
doris.config = {
read_json_by_line = "true"
format = "json"
}
}
}
