env {
  # 任务名称
  job.name = "JDBC_TO_HTTP_BATCH"
  # 批处理模式
  job.mode = "BATCH"
}

source {
  Jdbc {
    url = "jdbc:mysql://10.1.7.171:9030/ads"
    driver = "com.mysql.cj.jdbc.Driver"
    user = "root"
    password = "doris@test123"
    skip_analyze = "true"
    split.size = "100"
    sample_num = "100"
    table_path = "dws.DWS_SD_KH_QKZB_D"

    #where_condition = "where 324213"
    partition_column = "CALDAY"
    plugin_output = "source_table"
  }
}

transform {
  BatchJson {
    plugin_input = ["source_table"]
    plugin_output = "batched_data"
    batch.size = 3
    batch.fields = [
      { source = "CALDAY", target = "business_date", type = "STRING" }
      { source = "CALMONTH", target = "business_month", type = "INT" }
      { source = "KEQK", target = "amount", type = "STRING" }
    ]
    json.template = {
      data = "${batch.data}"
      status = "active"
      metadata = {
        source = "mysql"
        version = "1.0"
      }
      request_info = {
        request_id = "a1b2c3d4"
        timestamp = "2026-08-19 10:00:00"
      }
    }
  }
}

sink {
  # ---------- Sink 1: Console（用于调试）----------
  Console {
    plugin_input = ["batched_data"]
    log.print.data = true
    # 限制输出行数，避免刷屏
    limit = 10
  }

  # ---------- Sink 2: HTTP（目标接口）----------
}
