env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  Http {
    result_table_name = "http"
    url = "http://10.30.30.88:13005/app/datadev/publish-center/approve-page"
    method = "POST"
    format = "json"
    headers = {content-type="application/json;charset=UTF-8",loginToken="eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiI2MjQ4MzEzNDcyODkzOTUyIiwic3ViIjoiMjQyMDI0MDA3NyIsInN0IjoiMzI0MjNiMTEyMTM1NGNkYTg1MjUwNDU0Yjk4MjdlYmIiLCJ3b3JrY29kZSI6IjIwMjQwMDc3IiwiYXV0aCI6IkFETUlOIiwiZnNfZXhwaXJlcyI6IjIwMjUtMDMtMjggMDk6NTg6NDkiLCJtaWQiOjkwMDAwMDAwNTUsImZzX3VhdCI6InUtY3hDVXRNQzNCZnhVWFlhSzd2X3ZuczA0NHpmUWdsdEhNRzIwMDFFRzJjWXkiLCJ1c2VybmFtZSI6IjIwMjQwMDc3IiwicmVhbG5hbWUiOiLlvKDlhYnmt6EiLCJleHAiOjE3NDMyMDY5MzB9.kPFXntXmYXjnosm2mkOHSEEHNSV_u6nrcfu4ydiSpx7OTWK36Nv-5U2K3193Zk63PZ3XqlObxK9TjcFxtYTCBg"}
    schema = {
      fields = {
        taskFlowId = bigint
        taskFlowName = string
        taskFlowType = string
        total = int
        code = bigint
        list = string
      }
    }

    json_field = {
      taskFlowId = "$.data.list[*].taskFlowId"
      taskFlowName = "$.data.list[*].taskFlowName"
      taskFlowType = "$.data.list[*].taskFlowType"
      total = "$.data.total"
      code = "$.code"
      list = "$.data.list"
    }


  }
}

# Console printing of the read Http data
sink {
  Console {
    parallelism = 1
  }
}